name: Clean staging Env for Planning API
on:
  pull_request:
    types: [ closed ]
    paths:
      - planning-api/**
jobs:
  delete-stage:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    name: Delete stage environment
    environment:
      name: Dev
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.4
        with:
          workload_identity_provider: ${{ secrets.IDENTITY_POOL }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Delete service
        working-directory: planning-api
        run: |
          gcloud run services delete --region=${{ secrets.REGION }} --quiet planning-api-${{ github.event.pull_request.number }}
