name: Build planning API
on:
  push:
    branches:
      - '*'
      - '!main'
    paths:
      - planning-api/**
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - planning-api/**
jobs:
  tests:
    name: Unit and integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      MAVEN_OPTS: -Xms1024m -Xmx2048m -XX:MaxMetaspaceSize=1000m
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup docker
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Make maven executable
        working-directory: planning-api
        run: chmod +x ./mvnw
      - name: Run unit tests and sonar analyse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: planning-api
        run: ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
  package:
    name: Construct docker image
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment:
      name: Dev
    timeout-minutes: 15
    if: github.event_name == 'pull_request'
    needs:
      - tests
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup docker
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.4.4
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.IDENTITY_POOL }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Setup Gcloud
        uses: google-github-actions/setup-gcloud@v0.3.0
      - name: Login to GCR
        run: |
          gcloud auth configure-docker --quiet europe-west1-docker.pkg.dev
      - name: Prepare package
        working-directory: planning-api
        id: build
        run: |
          chmod +x ./mvnw
          ./mvnw -DskipTests clean package
          echo "::set-output name=short_sha::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: planning-api
          file: planning-api/src/main/docker/Dockerfile.jvm
          push: true
          tags: europe-west1-docker.pkg.dev/driving-monlabo-biz/planning/planning-api:${{ steps.build.outputs.short_sha }}
  deploy-staging:
    name: Deploy to staging
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    environment:
      name: Dev
      url: ${{ steps.deploy.outputs.url }}/swagger-ui/
    if: github.event_name == 'pull_request'
    needs:
      - package
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare service
        working-directory: planning-api
        run: |
          IMAGE=europe-west1-docker.pkg.dev/driving-monlabo-biz/planning/planning-api:$(echo ${GITHUB_SHA} | cut -c1-8)
          sed -i "s@SERVICE-NAME@planning-api-$PR_NUMBER@g" src/main/cloudrun/service.yaml
          sed -i "s@IMAGE@$IMAGE@g" src/main/cloudrun/service.yaml
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.4
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.IDENTITY_POOL }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Upload service
        uses: actions/upload-artifact@v2
        with:
          name: service
          path: ${{ github.workspace }}/planning-api/src/main/cloudrun/service.yaml
      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.7.0
        with:
          region: europe-west1
          metadata: ${{ github.workspace }}/planning-api/src/main/cloudrun/service.yaml
      - name: Make service public
        working-directory: planning-api
        run: |
          gcloud run services add-iam-policy-binding planning-api-${{ github.event.pull_request.number }} \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --region=${{ secrets.REGION }}
