name: Deploy main branch for Planning School
on:
  push:
    branches: [main]
    paths:
      - planning-school/**
jobs:
  create-image:
    name: Create docker image
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: 'read'
      id-token: 'write'
    environment:
      name: Dev
    steps:
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.4
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.IDENTITY_POOL }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Run unit tests and sonar analyse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: planning-school
        run: |
          chmod +x ./mvnw
          ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      - name: Create docker image
        working-directory: planning-school
        run: |
          ./mvnw -DskipTests clean package
          docker build -f src/main/docker/Dockerfile.jvm -t europe-west1-docker.pkg.dev/driving-monlabo-biz/planning/planning-school:${GITHUB_SHA} .
          docker tag europe-west1-docker.pkg.dev/driving-monlabo-biz/planning/planning-school:${GITHUB_SHA} europe-west1-docker.pkg.dev/driving-monlabo-biz/planning/planning-school:main
      - name: Authenticate to GCR and push image
        working-directory: planning-school
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          docker push europe-west1-docker.pkg.dev/driving-monlabo-biz/planning/planning-school:${GITHUB_SHA}
  deploy:
    runs-on: ubuntu-latest
    name: Deploy main branch
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: 
      name: Dev
      url: ${{ steps.deploy.outputs.url }}
    needs:
      - create-image
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Prepare service
      working-directory: planning-school
      run: |
        IMAGE=europe-west1-docker.pkg.dev/driving-monlabo-biz/planning/planning-school:${GITHUB_SHA}
        sed -i "s@SERVICE-NAME@planning-school@g" src/main/cloudrun/service.yaml
        sed -i "s@IMAGE@$IMAGE@g" src/main/cloudrun/service.yaml
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.4
      with:
        create_credentials_file: true
        workload_identity_provider: ${{ secrets.IDENTITY_POOL }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
    - id: deploy
      uses: google-github-actions/deploy-cloudrun@v0.7.0
      with:
        region: ${{ secrets.REGION }}
        metadata: planning-school/src/main/cloudrun/service.yaml