name: Build Planning school
on:
  push:
    branches:
      - '*'
      - '!main'
    paths:
      - planning-school/**
      - .github/workflows/**
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - planning-school/**
      - .github/workflows/**
jobs:
  tests:
    name: Unit and integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      MAVEN_OPTS: -Xms1024m -Xmx2048m -XX:MaxMetaspaceSize=1000m
    environment:
      name: Dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-school-tests
          restore-keys: ${{ runner.os }}-sonar
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.4.4
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.IDENTITY_POOL }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Run unit tests and sonar analyse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: planning-school
        run: |
          chmod +x ./mvnw
          ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
  package:
    name: Construct docker image
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment:
      name: Dev
    timeout-minutes: 15
    if: github.event_name == 'pull_request'
    needs:
      - tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.4.4
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.IDENTITY_POOL }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Create docker image
        working-directory: planning-school
        run: |
          chmod +x ./mvnw
          ./mvnw -DskipTests clean package
          docker build -f src/main/docker/Dockerfile.jvm -t europe-west1-docker.pkg.dev/driving-monlabo-biz/planning/planning-school:${GITHUB_SHA} .
      - name: Authenticate to GCR and push image
        working-directory: planning-school
        run: |
          gcloud auth configure-docker --quiet europe-west1-docker.pkg.dev
          docker push europe-west1-docker.pkg.dev/driving-monlabo-biz/planning/planning-school:${GITHUB_SHA}
  deploy-staging:
    name: Deploy to staging
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    environment:
      name: Dev
      url: ${{ steps.deploy.outputs.url }}
    if: github.event_name == 'pull_request'
    needs:
      - package
    steps:
      - uses: actions/checkout@v3
      - name: Prepare service
        working-directory: planning-school
        run: |
          IMAGE=europe-west1-docker.pkg.dev/driving-monlabo-biz/planning/planning-school:${GITHUB_SHA}
          sed -i "s@SERVICE-NAME@planning-school-$PR_NUMBER@g" src/main/cloudrun/service.yaml
          sed -i "s@IMAGE@$IMAGE@g" src/main/cloudrun/service.yaml
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
      - name: Upload service
        uses: actions/upload-artifact@v2
        with:
          name: service
          path: ${{ github.workspace }}/planning-school/src/main/cloudrun/service.yaml
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.4
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.IDENTITY_POOL }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.7.0
        with:
          region: ${{ secrets.REGION }}
          metadata: planning-school/src/main/cloudrun/service.yaml
      - name: Make service public
        working-directory: planning-school
        run: |
          gcloud run services add-iam-policy-binding planning-school-${{ github.event.pull_request.number }} \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --region=${{ secrets.REGION }}
