name: Clean staging Env for Planning School
on:
  pull_request:
    types: [ closed ]
    paths:
      - planning-school/**
jobs:
  delete-stage:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    name: Delete stage environment
    environment:
      name: Dev
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v4.4.0
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.IDENTITY_POOL }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Setup Gcloud
        uses: google-github-actions/setup-gcloud@v0.3.0
      - name: Delete service
        run: |
          gcloud run services delete --region=${{ secrets.REGION }} --quiet planning-school-${{ github.event.pull_request.number }}
